### PR TITLE
(resolves #83) Probability in tools needs parameter type

### LINKED ISSUE #83: Probability in tools needs parameter type
the probability function needs to have the "quantumstate" param changed to "quantum_state" and needs a union type of numpy array and quantumcircuit object.

### PR DESCRIPTION
**Pull request by fabie37**
# Pull Request
Requesting to pull changes to resolve issue #83 

## Description
Fixes issue presented in #83 

Please include a summary of the changes and the motivation behind them. If applicable, link to any related issues.

## Type of Change

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Documentation
- [x] Refactoring
- [ ] Other (please specify): 

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the documentation accordingly.
- [x] I ran `black` formatter on the codebase. (CI/CD will fail if neglected)
- [x] My code follows the project's coding style guidelines.

## Related Issues

- Closes #83 
- Related to #83 

## Screenshots (if applicable)
NA

## Additional Notes
Problem:
- Probability function needs Union[quantum_circuit, ndarray] type for quantum_state
- quantum_state rename from quantumstate

Issues:
- Importing quantum_circuit causes circular dependency
- quantum_circuit import base_core imports from tools qubit
- measure which is in tools imports probability which imports quantum_circuit

Solution:
- 1. Rename qunatumstate to quantum_state
- 2. Add Union type from typing
- 3. Remove qubit from tools and put into separate folder to separate imports this solve the dependency issue.

### CODE REVIEW

**Comment by brennanfreeze** [comment]
Hi @fabie37, thank you for checking these issues out! Looks great so far, would it possible to change the imports with an asterisk to an explicit import? This has been needed to be done and would be a big help thank you!

**Comment by parisosuch-dev** [comment]
> Hi @fabie37, thank you for checking these issues out! Looks great so far, would it possible to change the imports with an asterisk to an explicit import? This has been needed to be done and would be a big help thank you!

we could just accept it and solve that in another PR to cover issue #68

**Comment by brennanfreeze** [comment]
> > Hi @fabie37, thank you for checking these issues out! Looks great so far, would it possible to change the imports with an asterisk to an explicit import? This has been needed to be done and would be a big help thank you!
> 
> we could just accept it and solve that in another PR to cover issue #68

Works with me! Regardless, looks great.

**Review by parisosuch-dev — APPROVED** [review]
LGTM! Thanks :)

**Comment by fabie37** [comment]
Awesome, glad I could help!

**Pull request merged**
