### PR TITLE
Create black pipeline to check PRs

### PR DESCRIPTION
**Pull request by parisosuch-dev**
Pipelines baby -- pipelines.

### CODE REVIEW

**Comment by parisosuch-dev** [comment]
love how black checks the PR that creates the black pipeline

**Comment by parisosuch-dev** [comment]
gimme a sec to fix this @brennanfreeze

**Comment by parisosuch-dev** [comment]
ill fix this later -- just leave PR open for now 🤷🏼

**Comment by parisosuch-dev** [comment]
went ahead and just added an auto formatter for PRs instead of checking if the code is formatted to PEP8 styling. This works out better imo, making it to where people who contribute do not need to know about installing black formatter.

**Comment by brennanfreeze** [comment]
Looks good, definitely needed this

**Pull request merged**
