### PR TITLE
Remove Unused Imports

### PR DESCRIPTION
**Pull request by parisosuch-dev**
- Removed unused imports.
- Removed unused variables.

Solves issue #72.

### CODE REVIEW

**Comment by parisosuch-dev** [comment]
Why did my unit testing fail huh?

**Comment by brennanfreeze** [comment]
> Why did my unit testing fail huh?

The "check" variable, although a bit rustic was used to make sure that the user when calling the usage of a GPU without CUDA installed wouldnt throw an error, since Github's CI don't have access to one it failed:

```
 try:
                check = subprocess.check_output(["nvcc", "--version"]).decode()
                self.calculator = GpuCalculator(qubits, big_endian, prep)
except FileNotFoundError:
                print("ERROR: CUDA NOT INSTALLED. SWITCHING TO BASE...")

```

**Comment by parisosuch-dev** [comment]
Oh if that is the case, then we should just be calling `subprocess.check_output().decode()` without assigning the return to a variable. It should work then?

**Comment by parisosuch-dev** [comment]
@brennanfreeze I see what you are doing now, you are calling a command in subprocess to verify if `nvcc` is installed. If it isn't the command raises an error and you catch that error. There might be a better way to do this (i am not aware of one). I added the function call and just skipped the variable assignment and it works now. Thanks! 👍🏼

**Comment by brennanfreeze** [comment]
> @brennanfreeze I see what you are doing now, you are calling a command in subprocess to verify if `nvcc` is installed. If it isn't the command raises an error and you catch that error. There might be a better way to do this (i am not aware of one). I added the function call and just skipped the variable assignment and it works now. Thanks! 👍🏼

Pretty much! I agree with you there totally is that isnt using a unused variable, but I think for the time being.

**Review by brennanfreeze — APPROVED** [review]
Looks good!

**Pull request merged**
